export default [
  {
    date: '07/07/10',
    orderedBy: 'MAB',
    orderNumber: '10-218880',
    orderStatus: 'Pending - Shipment',
    orderType: 'Telehealth',
    items: [{name: 'Blood Pressure Unit', serialNumber: null}],
  },
  {
    date: '07/07/10',
    orderedBy: 'MAB',
    orderNumber: '10-228875',
    orderStatus: 'Pending - Shipment',
    orderType: 'Telehealth',
    items: [{name: 'Glucose Meter', serialNumber: null}],
  },
  {
    date: '07/07/10',
    orderedBy: 'MAB',
    orderNumber: '10-218880',
    orderStatus: 'Pending - Shipment',
    orderType: 'Batteries',
    items: [{name: 'ALKAA', serialNumber: null}],
  },
  {
    date: '07/07/10',
    orderedBy: 'MAB',
    orderNumber: '10-218860',
    orderStatus: 'Pending - Shipment',
    orderType: 'Batteries',
    items: [{name: 'ALKAAA', serialNumber: null}],
  },
  {
    date: '06/25/10',
    orderedBy: 'MAB',
    orderNumber: '10-218890',
    orderStatus: 'Complete',
    orderType: 'Custom Hearing Aids',
    items: [
      {name: 'Touch 6 Ric', serialNumber: null},
      {name: 'Touch 6 Ric', serialNumber: null},
    ],
  },
  {
    date: '09/02/09',
    orderedBy: 'MAB',
    orderNumber: '10-218859',
    orderStatus: 'Complete',
    orderType: 'Custom Hearing Aids',
    serialNumber: null,
    items: [
      {name: 'Vector iM16 ITE', serialNumber: null},
      {name: 'Vector iM16 ITE', serialNumber: null},
    ],
  },
  {
    date: '05/29/08',
    orderedBy: 'KLG',
    orderNumber: '10-218880',
    orderStatus: 'Complete',
    orderType: 'Telehealth',
    serialNumber: null,
    items: [{name: 'ELEVA 11 CIC', serialNumber: null}],
  },
  {
    date: '05/29/08',
    orderedBy: 'KLG',
    orderNumber: '10-218880',
    orderStatus: 'Complete',
    orderType: 'Telehealth',
    serialNumber: null,
    items: [{name: 'ELEVA 11 CIC', serialNumber: null}],
  },
  {
    date: '05/07/08',
    orderedBy: 'MAB',
    orderNumber: '10-218880',
    orderStatus: 'Complete',
    orderType: 'Custom Hearing Aids',
    items: [
      {name: 'YUU HIGH POWER BTE', serialNumber: '0507084L'},
      {name: 'YUU HIGH POWER BTE', serialNumber: '0507084R'},
      {name: 'SMART CONTROL', serialNumber: '0507084X'},
    ],
  },
  {
    date: '05/07/08',
    orderedBy: 'PJU',
    orderNumber: '10-218880',
    orderStatus: 'Complete',
    orderType: 'Batteries',
    items: [{name: 'ZA312', serialNumber: null}],
  },
];
